#!/usr/bin/env bash
# Build and publish the demo to GitHub Pages (gh-pages branch, served from /).
#
#   ./scripts/deploy-pages.sh
#
# Differs from the container build in two ways, both deliberate:
#   - VITE_BASE is the repo sub-path, because Pages serves from
#     https://<user>.github.io/<repo>/ rather than the site root. Every runtime
#     fetch (config YAML, thumbnails, SDK assets) resolves against it.
#   - SDK assets come from the Esri CDN instead of being bundled, which takes
#     the branch from ~100MB to ~17MB. The container still bundles them so it
#     works on networks that block js.arcgis.com.
set -euo pipefail

REPO="${PAGES_REPO:-idfg-hunt-planner-mapcenter}"
OWNER="${PAGES_OWNER:-idahoboy}"
REMOTE="git@github.com:${OWNER}/${REPO}.git"

# Optional sub-path, e.g. PAGES_SUBPATH=preview/brainstorming
#
# Pages serves one site per repository, so a second build cannot have its own
# branch. It goes in a sub-directory of the same gh-pages branch instead —
# which means this must ADD to what is already published rather than replacing
# it, or deploying a preview would silently delete the main demo.
SUBPATH="${PAGES_SUBPATH:-}"

# Pin the CDN to the SDK version actually installed, so assets and code agree.
SDK_MINOR="$(node -p "require('@arcgis/core/package.json').version.split('.').slice(0,2).join('.')")"

if [ -n "$SUBPATH" ]; then
  BASE="/${REPO}/${SUBPATH}/"
else
  BASE="/${REPO}/"
fi

echo "building for ${BASE} against SDK ${SDK_MINOR} assets"
rm -rf dist
VITE_BASE="$BASE" \
VITE_ESRI_ASSETS_PATH="https://js.arcgis.com/${SDK_MINOR}/@arcgis/core/assets" \
  npm run build

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if [ -n "$SUBPATH" ]; then
  # Start from what is already published so the root demo survives.
  git clone -q --depth 1 --branch gh-pages "$REMOTE" "$WORK"
  rm -rf "${WORK:?}/${SUBPATH}"
  mkdir -p "$WORK/$SUBPATH"
  cp -R dist/. "$WORK/$SUBPATH/"
  cp "$WORK/$SUBPATH/index.html" "$WORK/$SUBPATH/404.html"
  MSG="Publish ${SUBPATH} preview

Generated by scripts/deploy-pages.sh. Added alongside the root demo, which is
untouched — Pages serves one site per repository, so previews live in a
sub-directory rather than a branch of their own."
else
  cp -R dist/. "$WORK/"
  cp "$WORK/index.html" "$WORK/404.html"   # SPA fallback for unknown paths
  MSG="Deploy Map Center demo to GitHub Pages

Generated from main by scripts/deploy-pages.sh; do not edit this branch."
fi

touch "$WORK/.nojekyll"          # keep Pages from hiding _-prefixed paths

cd "$WORK"
if [ ! -d .git ]; then
  git init -q -b gh-pages
fi
git add -A
git commit -q -m "$MSG" || echo "  (nothing changed)"
git push -q "$REMOTE" HEAD:gh-pages

echo "deployed -> https://${OWNER}.github.io/${REPO}/${SUBPATH:+$SUBPATH/}"
